### ISSUE TITLE
Add hover effect to navbar.

### ISSUE THREAD

**Issue by rtuwrukjj** [rtuwrukjj/risCoda#3]

**Comment by kanishk6103** [comment]
can i do it?

**Comment by chhavi-rana** [comment]
Please assign this issue to me.

**Comment by kanishk6103** [comment]
What style do you exactly want when hovered?

**Comment by rtuwrukjj** [comment]
> What style do you exactly want when hovered?

Do as you wish. Just keep in mind that it should look presentable.
